# Generated by Django 3.2.5 on 2021-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='stat_defensa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jugador',
            name='stat_fuerza',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jugador',
            name='stat_resistencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jugador',
            name='stat_velocidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimient',
            field=models.DateTimeField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
