# Generated by Django 3.2.5 on 2021-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_detalle_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(default='xD', max_length=100),
        ),
    ]
