# Generated by Django 3.2.5 on 2021-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_juego_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
