# Generated by Django 3.2.5 on 2021-07-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210727_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='stat_defensa',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='stat_fuerza',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='stat_resistencia',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='stat_velocidad',
        ),
        migrations.AddField(
            model_name='historial',
            name='juego',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.juego'),
        ),
        migrations.AddField(
            model_name='historial',
            name='promedio_stat_defensa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historial',
            name='promedio_stat_fuerza',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historial',
            name='promedio_stat_resistencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historial',
            name='promedio_stat_velocidad',
            field=models.IntegerField(default=1),
        ),
    ]
