# Generated by Django 3.2.5 on 2021-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210729_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='pais',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
    ]
