# Generated by Django 3.2.5 on 2021-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210729_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
